### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by danrabbit** [alcinnz/odysseus-web#6]
Odysseus crashes on start with the following:

```
[ERROR 09:04:05.123380] database.vala:45: Failed to load UI state! unable to open database file
Trace/breakpoint trap (core dumped)
```

**Comment by alcinnz** [comment]
I've just diagnosed the issue and I now understand why I haven't been seeing this issue before myself. 

I need to create a configuration folder for the database and WebKit files before I attempt to open it, but I've already created the folder before I created the database so it appeared to work for me. 

A fix will be released soon.

**Comment by alcinnz** [comment]
I'm pretty sure I've fixed it now, though I will try installing Odysseus on a different computer myself just to make sure. 

But I'm uploading a new release just to make sure.

**Comment by alcinnz** [comment]
P.S. Thank you for pointing this out, next time I will do a test install on a clean machine before I release any future projects.

**Comment by alcinnz** [comment]
I've finally managed to get a VM up with the tools I needed to build Odysseus, and as such I can double-confirm this issue appears truly fixed.
